### ISSUE TITLE
Suffix generateName is always 62135596800

### ISSUE THREAD

**Issue by yutachaos** [argoproj/gitops-engine#181]
#  Description
62135596800 is added to suffix when using generateName

### example yaml

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  generateName: some-operation-
  annotations:
    argocd.argoproj.io/hook: PreSync
```
`e.g some-operation-{git_hash}-presync-62135596800`

## Question
Is this intentional behavior?
If you get the same thing every time, I don't think you need to this suffix.

Also, I would like to keep the Job every time by using generateName, but if it is the same commit as it is now, the Job will be deleted.

## Cause
- This is because the time is not inputed in startedAt in the func NewContext, so the default value of time.Time is included.
    - https://github.com/argoproj/gitops-engine/blob/master/pkg/sync/sync_context.go#L167-L183
