### ISSUE TITLE
Please add SealedSecret kind in the priority for app sync aswell

### ISSUE THREAD

**Issue by nclfinalis** [argoproj/gitops-engine#552]
```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
```

https://github.com/argoproj/gitops-engine/blob/bc9ce5764fa306f58cf59199a94f6c968c775a2d/pkg/sync/sync_tasks.go#L27-L66
